defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-

      - run:
          name: Installing node modules
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: "~"
          paths:
            - repo

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: "~"

      - run:
          name: Testing
          command: npm test
      - run:
          name: print token
          command: echo $npm_TOKEN

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: "~"

      - run:
          name: Authenticate with registry
          command: export "//registry.npmjs.org/:_authToken=$npm_TOKEN"

      - run:
          name: Publishing package to npm
          command: npm publish


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - test:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - dev
          requires:
            - test
      - post-deploy:
          filters:
            branches:
              only:
                - dev
          requires:
            - deploy
  build_and_deploy_master:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
           - test
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - hold
